# Site settings
title: Cale Dunlap
email: cale.dunlap@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caledunlap.com" # the base hostname & protocol for your site
twitter_username: dunlapcj
gplus_username: CaleDunlap
linkedin_username: cdunlap
github_username:  cdunlap

# Build settings
markdown: kramdown