// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact Page documents
 */
interface ContactDocumentData {
  /**
   * Title field in *Contact Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Content field in *Contact Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * `slices` field in *Contact Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>;
}

/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type HomeDocumentDataSlicesSlice = HomeHeroSlice;

/**
 * Item in *Homepage → Education*
 */
export interface HomeDocumentDataEducationItem {
  /**
   * School field in *Homepage → Education*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.education[].school
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  school: prismic.TitleField;

  /**
   * Location field in *Homepage → Education*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.education[].location
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.TitleField;

  /**
   * Dates field in *Homepage → Education*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.education[].dates
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  dates: prismic.TitleField;

  /**
   * Degree field in *Homepage → Education*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.education[].degree
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  degree: prismic.TitleField;

  /**
   * Other field in *Homepage → Education*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.education[].other
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  other: prismic.RichTextField;
}

/**
 * Item in *Homepage → certificates*
 */
export interface HomeDocumentDataCertificatesItem {
  /**
   * Title field in *Homepage → certificates*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.certificates[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Certificate Date field in *Homepage → certificates*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: home.certificates[].certificate_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  certificate_date: prismic.DateField;

  /**
   * Institution field in *Homepage → certificates*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.certificates[].institution
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  institution: prismic.TitleField;

  /**
   * Certificate Number field in *Homepage → certificates*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.certificates[].certificate_number
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  certificate_number: prismic.TitleField;

  /**
   * Certificate URL field in *Homepage → certificates*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.certificates[].certificate_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  certificate_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Homepage → Work History*
 */
export interface HomeDocumentDataWorkHistoryItem {
  /**
   * Company field in *Homepage → Work History*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.work_history[].company
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  company: prismic.TitleField;

  /**
   * Company Website field in *Homepage → Work History*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.work_history[].company_website
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company_website: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Location field in *Homepage → Work History*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.work_history[].location
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.TitleField;

  /**
   * Job Title field in *Homepage → Work History*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.work_history[].job_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  job_title: prismic.TitleField;

  /**
   * Dates field in *Homepage → Work History*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.work_history[].dates
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  dates: prismic.TitleField;
}

/**
 * Item in *Homepage → Skills*
 */
export interface HomeDocumentDataSkillsItem {
  /**
   * Name field in *Homepage → Skills*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skills[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Subjective Rating (0-100) field in *Homepage → Skills*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skills[].subjective_rating
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  subjective_rating: prismic.NumberField;

  /**
   * Personal Experience (Years) field in *Homepage → Skills*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skills[].personal_experience
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  personal_experience: prismic.NumberField;

  /**
   * Professional Experience (Years) field in *Homepage → Skills*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skills[].professional_experience
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  professional_experience: prismic.NumberField;
}

/**
 * Item in *Homepage → Volunteer Service*
 */
export interface HomeDocumentDataVolunteerServiceItem {
  /**
   * Organization field in *Homepage → Volunteer Service*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Organization Name
   * - **API ID Path**: home.volunteer_service[].organization
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  organization: prismic.TitleField;

  /**
   * Dates field in *Homepage → Volunteer Service*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Dates
   * - **API ID Path**: home.volunteer_service[].dates
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  dates: prismic.TitleField;

  /**
   * Organization Website field in *Homepage → Volunteer Service*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Organization Website
   * - **API ID Path**: home.volunteer_service[].organization_website
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  organization_website: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Location field in *Homepage → Volunteer Service*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Location
   * - **API ID Path**: home.volunteer_service[].location
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  location: prismic.TitleField;

  /**
   * Role field in *Homepage → Volunteer Service*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Role
   * - **API ID Path**: home.volunteer_service[].role
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.TitleField;

  /**
   * Responsibilities field in *Homepage → Volunteer Service*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Responsibilities
   * - **API ID Path**: home.volunteer_service[].responsibilities
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  responsibilities: prismic.RichTextField;
}

/**
 * Item in *Homepage → Publications*
 */
export interface HomeDocumentDataPublicationsItem {
  /**
   * Title field in *Homepage → Publications*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title
   * - **API ID Path**: home.publications[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Publisher field in *Homepage → Publications*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Publisher
   * - **API ID Path**: home.publications[].publisher
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  publisher: prismic.TitleField;

  /**
   * Publish Date field in *Homepage → Publications*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Publish Date
   * - **API ID Path**: home.publications[].publish_date
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  publish_date: prismic.TitleField;

  /**
   * Role field in *Homepage → Publications*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Role
   * - **API ID Path**: home.publications[].role
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.TitleField;

  /**
   * URL field in *Homepage → Publications*
   *
   * - **Field Type**: Link
   * - **Placeholder**: URL
   * - **API ID Path**: home.publications[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Description field in *Homepage → Publications*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description
   * - **API ID Path**: home.publications[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Content for Homepage documents
 */
interface HomeDocumentData {
  /**
   * Hero TItle field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Hero TItle
   * - **API ID Path**: home.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_title: prismic.TitleField;

  /**
   * Hero Lead field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hero_lead
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_lead: prismic.RichTextField;

  /**
   * Hero Content field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Hero Content
   * - **API ID Path**: home.hero_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_content: prismic.RichTextField;

  /**
   * Contact Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Contact Title
   * - **API ID Path**: home.contact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_title: prismic.TitleField;

  /**
   * Contact Content field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contact content
   * - **API ID Path**: home.contact_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_content: prismic.RichTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Institutional Education Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Institutional Education
   * - **API ID Path**: home.institutional_education_title
   * - **Tab**: Education
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  institutional_education_title: prismic.TitleField;

  /**
   * Education field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.education[]
   * - **Tab**: Education
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  education: prismic.GroupField<Simplify<HomeDocumentDataEducationItem>>;

  /**
   * Certificates and Courses Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Certificates & Courses
   * - **API ID Path**: home.certificates_courses_title
   * - **Tab**: Education
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  certificates_courses_title: prismic.TitleField;

  /**
   * certificates field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.certificates[]
   * - **Tab**: Education
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  certificates: prismic.GroupField<
    Simplify<HomeDocumentDataCertificatesItem>
  > /**
   * Work History Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Work History
   * - **API ID Path**: home.work_history_title
   * - **Tab**: Work History
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  work_history_title: prismic.TitleField;

  /**
   * Work History field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.work_history[]
   * - **Tab**: Work History
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  work_history: prismic.GroupField<
    Simplify<HomeDocumentDataWorkHistoryItem>
  > /**
   * Skills Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Skills
   * - **API ID Path**: home.skills_title
   * - **Tab**: Skills
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  skills_title: prismic.TitleField;

  /**
   * Skills Content field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skills_content
   * - **Tab**: Skills
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  skills_content: prismic.RichTextField;

  /**
   * Skills field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.skills[]
   * - **Tab**: Skills
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skills: prismic.GroupField<Simplify<HomeDocumentDataSkillsItem>> /**
   * Volunteer Service Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Volunteer Service Title
   * - **API ID Path**: home.volunteer_service_title
   * - **Tab**: Volunteer Service
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  volunteer_service_title: prismic.TitleField;

  /**
   * Volunteer Service field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.volunteer_service[]
   * - **Tab**: Volunteer Service
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  volunteer_service: prismic.GroupField<
    Simplify<HomeDocumentDataVolunteerServiceItem>
  > /**
   * Publications Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Publications Title
   * - **API ID Path**: home.publications_title
   * - **Tab**: Publications
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  publications_title: prismic.TitleField;

  /**
   * Publications field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.publications[]
   * - **Tab**: Publications
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  publications: prismic.GroupField<Simplify<HomeDocumentDataPublicationsItem>>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item content in *Project → Slice zone → Project Photos → Items*
 */
export interface ProjectDocumentDataBodyProjectPhotosSliceItem {
  /**
   * Project Photo field in *Project → Slice zone → Project Photos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.body[].project_photos.items.project_photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  project_photo: prismic.ImageField<never>;
}

/**
 * Slice for *Project → Slice zone*
 */
export type ProjectDocumentDataBodyProjectPhotosSlice = prismic.Slice<
  "project_photos",
  Record<string, never>,
  Simplify<ProjectDocumentDataBodyProjectPhotosSliceItem>
>;

/**
 * Item content in *Project → Slice zone → Project Videos → Items*
 */
export interface ProjectDocumentDataBodyProjectVideosSliceItem {
  /**
   * Project Video field in *Project → Slice zone → Project Videos → Items*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: project.body[].project_videos.items.project_video
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  project_video: prismic.EmbedField;
}

/**
 * Slice for *Project → Slice zone*
 */
export type ProjectDocumentDataBodyProjectVideosSlice = prismic.Slice<
  "project_videos",
  Record<string, never>,
  Simplify<ProjectDocumentDataBodyProjectVideosSliceItem>
>;

type ProjectDocumentDataBodySlice =
  | ProjectDocumentDataBodyProjectPhotosSlice
  | ProjectDocumentDataBodyProjectVideosSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Project Hero Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Hero Video field in *Project*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project.hero_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Project Name field in *Project*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: project.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Demo Video field in *Project*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project.demo_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  demo_video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Project Description field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Live URL field in *Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.live_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  live_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Description (long) field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description_long
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description_long: prismic.RichTextField /**
   * Slice zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.body[]
   * - **Tab**: Media
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  body: prismic.SliceZone<ProjectDocumentDataBodySlice>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Item in *Project List → Projects*
 */
export interface ProjectListDocumentDataProjectsItem {
  /**
   * Project field in *Project List → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_list.projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

/**
 * Content for Project List documents
 */
interface ProjectListDocumentData {
  /**
   * Hero Title field in *Project List*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: project_list.hero_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_title: prismic.TitleField;

  /**
   * Hero Lead field in *Project List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_list.hero_lead
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_lead: prismic.RichTextField;

  /**
   * Hero Content field in *Project List*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_list.hero_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_content: prismic.RichTextField;

  /**
   * Projects Title field in *Project List*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Projects
   * - **API ID Path**: project_list.projects_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  projects_title: prismic.TitleField;

  /**
   * Projects field in *Project List*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_list.projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<Simplify<ProjectListDocumentDataProjectsItem>>;
}

/**
 * Project List document from Prismic
 *
 * - **API ID**: `project_list`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectListDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectListDocumentData>,
    "project_list",
    Lang
  >;

/**
 * Item in *Skill → Associated Projects*
 */
export interface SkillDocumentDataAssociatedProjectsItem {
  /**
   * Project field in *Skill → Associated Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.associated_projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project">;
}

/**
 * Content for Skill documents
 */
interface SkillDocumentData {
  /**
   * Name field in *Skill*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Subjective Rating field in *Skill*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.subjective_rating
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  subjective_rating: prismic.NumberField;

  /**
   * Professional Experience field in *Skill*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.professional_experience
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  professional_experience: prismic.NumberField;

  /**
   * Personal Experience field in *Skill*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.personal_experience
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  personal_experience: prismic.NumberField;

  /**
   * Associated Projects field in *Skill*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: skill.associated_projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  associated_projects: prismic.GroupField<
    Simplify<SkillDocumentDataAssociatedProjectsItem>
  >;
}

/**
 * Skill document from Prismic
 *
 * - **API ID**: `skill`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SkillDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<SkillDocumentData>, "skill", Lang>;

export type AllDocumentTypes =
  | ContactDocument
  | HomeDocument
  | ProjectDocument
  | ProjectListDocument
  | SkillDocument;

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *HomeHero*
 */
type HomeHeroSliceVariation = HomeHeroSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `home_hero`
 * - **Description**: HomeHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeHeroSlice = prismic.SharedSlice<
  "home_hero",
  HomeHeroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      HomeDocumentDataEducationItem,
      HomeDocumentDataCertificatesItem,
      HomeDocumentDataWorkHistoryItem,
      HomeDocumentDataSkillsItem,
      HomeDocumentDataVolunteerServiceItem,
      HomeDocumentDataPublicationsItem,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataBodyProjectPhotosSliceItem,
      ProjectDocumentDataBodyProjectVideosSliceItem,
      ProjectDocumentDataBodySlice,
      ProjectListDocument,
      ProjectListDocumentData,
      ProjectListDocumentDataProjectsItem,
      SkillDocument,
      SkillDocumentData,
      SkillDocumentDataAssociatedProjectsItem,
      AllDocumentTypes,
      HomeHeroSlice,
      HomeHeroSliceVariation,
      HomeHeroSliceDefault,
    };
  }
}
